config/routes.rb
Rails.application.routes.draw do
  # get 'reviews/new'
  # get 'filmes/show'
  # get 'filmes/create'
  # get 'filmes/edit'
  # get 'filmes/update'
  # get 'filmes/destroy'
  devise_for :users
  root to: 'pages#home'
  # resources :filmes
  resources :filmes do
    resources :reviews, only: [:new, :create]
  end
  # resources :reviews do
  #   patch 'hide-review', to: 'reviews#hide', as: hide
  # end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/filme.rb
class Filme < ApplicationRecord
    has_many :reviews, dependent: :delete_all
    
    validates :titulo, presence: true, uniqueness: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :filme
  belongs_to :user

  validates :rating, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :filmes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/filmes_controller.rb
class FilmesController < ApplicationController
    before_action :set_filme, except: [:index, :new, :create]

    def index
        @filmes = Filme.all
    end
  
    def show
        @review = Review.new
        @reviews = Review.where(filme: @filme)
        # raise
        # @reviews = Review.where(filme_id: @filme.id, visible: true)
        # raise
    end

    def new
        @filme = Filme.new
    end

    def create
        @filme = Filme.new(filme_params)
        if @filme.save
            redirect_to filmes_path(@filme)
        else
            render :new
        end
    end

    def edit
    end

    def update
        if @filme.update(filme_params)
            redirect_to filme_path(@filme)
        else
            render :edit
        end
    end

    def destroy
        @filme.destroy
        redirect_to filmes_path
    end
    
    private def set_filme
        @filme = Filme.find(params[:id])
    end
        
    def filme_params
        params.require(:filme).permit(:titulo, :diretor, :data_lancamento, :sinopse)    
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
    def new
        @review = Review.new
        @restaurant = Filme.find(params[:filme_id])
    end

    def create
        @review = Review.new(review_params)
        @filme = Filme.find(params[:filme_id])
        @review.filme = @filme
        @review.user = current_user
        @review.save
        redirect_to filme_path(@filme)
    end

    def hide
        @review = Review.find(params[:review_id])
        @review.visible = false
        @review.save
        redirect_to filme_path(@review.filme)
    end

    private def review_params
        params.require(:review).permit(:content, :rating)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/filmes/_form.html.erb
<%= simple_form_for filme do |f| %>
  <%= f.input :titulo %>
  <%= f.input :diretor %>  
  <%= f.input :data_lancamento, { :start_year => 1900, order: [:day, :month, :year] } %> 
  <%= f.input :sinopse %>
  <%= f.submit %>
<% end %>

app/views/filmes/create.html.erb
<h1>Filmes#create</h1>
<p>Find me in app/views/filmes/create.html.erb</p>

app/views/filmes/edit.html.erb
<%= link_to 'Voltar', filmes_path, class: 'btn btn-light'%>

<div class="container">
    <h1>Editar Filme</h1>
    
    <%= render 'form', filme: @filme %>
</div>

app/views/filmes/index.html.erb
<h1>Filmes disponíveis (<%=@filmes.count %>):</h1>
<ul>
    <%= link_to 'Adicionar novo filme', new_filme_path, class:"btn btn-primary" %>
    <% @filmes.each do |filme| %>
</ul>
<ul>
    <li><b>Título:</b> "<%= filme.titulo %>"
    <ul>
        <li><b>Diretor:</b> <%= filme.diretor %></li>
        <%= link_to 'Ver detalhes', filme_path(filme), class:"btn btn-info" %>
    </ul>
    </li>
<ul>
</ul>
</ul>
<% end %>

app/views/filmes/new.html.erb
<div class="container">
    <h1 id='title'>Adicionar novo filme</h1>

    <%= render 'form', filme: @filme %>
</div>

app/views/filmes/show.html.erb
<div class="canto-superior-direito">
    <%= link_to 'Voltar', filmes_path, class: 'btn btn-light'%>
</div>
<div class="container">
    <h1>Sobre o filme:</h1>

    <b>Título:</b> <%= @filme.titulo %>
    </br>
    <b>Diretor:</b> <%= @filme.diretor %>
    </br>
    <b>Descrição:</b> <%= @filme.sinopse %>
    </br>
    <b>Data de Lançamento:</b>
    <% if @filme.data_lancamento %>
        <%= @filme.data_lancamento.day %>/<%= @filme.data_lancamento.month%>/<%= @filme.data_lancamento.year %>
    <% else %>
        unknown date
    <% end %>
    </br>
    <%= link_to 'editar',  edit_filme_path(@filme), method: :get, class:"btn btn-secondary" %>
    <%= link_to 'deletar', filme_path(@filme), method: :delete, data: { confirm: "Tem certeza que deseja apagar este filme?"}, class:"btn btn-danger" %>

    </br>
    </br>
    <h5>Avaliações:</h5>
    <% @reviews.each do |review| %>
        <div id="accordion-<%= review.id %>">
            <div class="card">
                <div class="card-header" id="headingOne-<%=review.id%>">
                    <h5 class="mb-0">
                        <button class="btn btn-link" data-toggle="collapse" data-target="#collapseOne-<%=review.id%>" aria-expanded="false" aria-controls="collapseOne-<%=review.id%>">
                            <% review.rating.times do  %>
                                <i class="bi bi-star-fill"></i>
                            <% end %>

                            <% (5 - review.rating).times do %>
                                <i class="bi bi-star"></i>
                            <% end %>
                            -
                            <%= review.user.email %>
                        </button>
                    </h5>
                </div>

                <div id="collapseOne-<%=review.id%>" class="collapse show" aria-labelledby="headingOne-<%=review.id%>" data-parent="#accordion-<%=review.id%>">
                    <div class="card-body">
                        <%= review.content %>
                        <%
=begin%>
 <%= link_to "hide", review_hide_path(review), method: :patch, class: 'btn btn-primary btn-sm' %>    
<%
=end%>
                    </div>
                </div>
            </div>
        </div>      
    <% end %>

    <%= render 'reviews/new'%>
    
</div>

app/views/filmes/update.html.erb
<h1>Filmes#update</h1>
<p>Find me in app/views/filmes/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MoviesOnRails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>

    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="home-banner">
    <h1>Movies on Rails</h1>

    <p>
        <span id="banner-typed-text"></span>
    </p>
    <%= link_to "Ver Filmes Disponíveis", filmes_path, class: "btn btn-primary" %>
    </div>
</div>

app/views/reviews/_new.html.erb
</br>
<h5>Escreva sua opinião:</h5>

<%= simple_form_for [@filme, @review] do |f| %>
    <%= f.input :content %>
    <%
=begin%>
 <span class=”glyphicon glyphicon-star-empty”></span> 
<%
=end%>
    <%= f.input :rating, collection: [1, 2, 3, 4, 5] %>
    <%= f.submit %>
<% end %>
<br/>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "/", class: "navbar-brand" do %>
    <%= image_tag "https://img-premium.flaticon.com/png/512/1175/premium/1175460.png?token=exp=1624560987~hmac=73bf898cd6366ad2a94ef7b21db7fffa" %>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Filmes", filmes_path, class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "https://image.flaticon.com/icons/png/512/64/64572.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <div class="dropdown-item">
                <p>Seja bem vindo, <%= current_user.email %></p>
            </div>
            <%
=begin%>
 <%= link_to "Another action", "#", class: "dropdown-item" %> 
<%
=end%>
            <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>